### ISSUE TITLE
[Not an issue] - Requesting for approach to setup specific tools

### ISSUE THREAD

**Issue by Elamurugan-Nallathambi** [aaronpowell/system-init#1]
**Experience:**
This is great script which does every tool probably going to be required for someone who starts new into development using windows machines.

It installed so many tools and having error in `nvm` , `terminal-icons` , `oh-my-posh` tools and in my case I think I am having more than all tools I required and I did node setup manually [that is the only thing extra I did] - so all in all its so good and helpful so thanks a bunch 🙏.

**Request:** 

I am looking for way to specify either only few tools wants to install or ignore specific set of tools in this auto install. It will be helpful to get your insight into this.

**Comment by aaronpowell** [comment]
The goal of this repo isn't to have something that someone could just pull and use on their own setup, unless they are running exactly the same hardware as me, it's meant to be a starting point for others who want to do automated machine setup.

If there's things you'd like to adapt for your workflow, you're welcome to fork this repo and use it that way.
